[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "14.15.0"
  
[[headers]]
  X-Frame-Options: SAMEORIGIN

[[plugins]]
  package = "@netlify/plugin-gatsby"
